services:
    nginx:
        hostname: "secret-santa-api-nginx"
        image: docker.io/wardenenv/nginx:1.16
        volumes:
            - ./:/var/www/html:cached
        environment:
            - NGINX_PUBLIC=/public
        ports:
            - "8888:80"
        depends_on:
            - php-fpm

    php-fpm:
        hostname: "secret-santa-api-php-fpm"
        image: docker.io/wardenenv/php-fpm:8.3
        environment:
            - SSH_AUTH_SOCK="/tmp/ssh-auth.sock"
            - COMPOSER_VERSION=2
            - COMPOSER_MEMORY_LIMIT=-1
        volumes:
            - ./:/var/www/html:cached
        depends_on:
            - db

    db:
        hostname: "secret-santa-api-mariadb"
        image: docker.io/wardenenv/mariadb:10.4
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-symfony}
            - MYSQL_DATABASE=${MYSQL_DATABASE:-symfony}
            - MYSQL_USER=${MYSQL_USER:-symfony}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD:-symfony}
        volumes:
            - dbdata:/var/lib/mysql

volumes:
    dbdata:
